apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/researchwork/frontendemo:v9
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: frontend
    release: hsop-prometheus
  name: frontend
  namespace: observability
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
status:
        loadBalancer: {}
