apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app: backend
    release: hsop-prometheus
  name: backend
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: web
    targetPort: 8080
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      app: backend
